name: Build the game

on:
  pull_request:
    branches: [master]
  push:
    branches: [developmentalist]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            target: windows
            artifactName: Modded-PE-0.0.1_windows
            artifactPath: export/release/windows/bin/*

          - name: Linux
            os: ubuntu-22.04
            target: linux
            artifactName: Modded-PE-0.0.1_linux
            artifactPath: export/release/linux/bin/*

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Haxe libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install hxcpp
          haxelib list

      - name: Lime setup
        run: haxelib run lime setup

      - name: Build (${{ matrix.target }})
        run: |
          lime build ${{ matrix.target }} -release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.artifactPath }}
