name: Build the game

on:
  pull_request:
    branches: [master]
  push:
    branches: [developmentalist]
  workflow_dispatch:

jobs:
  BuildCaches:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Desktop
            os: ubuntu-latest
            setupScript: sh ./setup/unix.sh
            CACHE_NAME: Modded-PE-0.0.1.desktop-cache

    uses: ./.github/workflows/dependencies.yml
    with:
      os: ${{ matrix.os }}
      CACHE_NAME: ${{ matrix.CACHE_NAME }}
      setupScript: ${{ matrix.setupScript }}

  BuildDesktop:
    name: ${{ matrix.name }}
    needs: BuildCaches
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            exportPath: windows
            artifactName: Modded-PE-0.0.1_windows
            artifactPath: export\release\windows\bin\*
            cachePath: Modded-PE-0.0.1.build-windows
            cacheLibrariesPath: Modded-PE-0.0.1.desktop-cache

          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            exportPath: linux
            artifactName: Modded-PE-0.0.1_linux
            artifactPath: export/release/linux/bin/*
            cachePath: Modded-PE-0.0.1.build-linux
            cacheLibrariesPath: Modded-PE-0.0.1.desktop-cache

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{ matrix.cachePath }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
