name: Build the game

on:
  pull_request:
    branches: [master]
  push:
    branches: [developmentalist]
  workflow_dispatch:

jobs:
  BuildWindows:
    name: Build Windows
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Haxe
        run: |
          choco install haxe -y
          refreshenv

      - name: Install Haxelib dependencies
        run: |
          haxelib install lime
          haxelib install openfl

      - name: Clean build
        run: lime clean windows

      - name: Build Windows
        run: lime build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modded-PE_0.0.1_windows
          path: export/release/windows/bin/
